# Generated by Django 6.0.1 on 2026-02-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value_type', models.CharField(choices=[('bool', 'Bool'), ('int', 'Int'), ('float', 'Float'), ('string', 'String'), ('json', 'JSON')], default='string', max_length=16)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('chat', 'Chat'), ('onboarding', 'Onboarding'), ('inferred', 'Inferred'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('confidence', models.FloatField(default=1.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key'], name='users_userp_user_id_0c4075_idx'), models.Index(fields=['user', 'updated_at'], name='users_userp_user_id_49e33a_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=64)),
                ('age_range', models.CharField(blank=True, max_length=32)),
                ('household_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location_zip', models.CharField(blank=True, max_length=16)),
                ('income_range', models.CharField(blank=True, max_length=32)),
                ('financial_goal', models.CharField(blank=True, choices=[('save_more', 'Save more'), ('invest', 'Invest'), ('reduce_debt', 'Reduce debt'), ('build_credit', 'Build credit'), ('control_subs', 'Control subscriptions'), ('other', 'Other')], max_length=32)),
                ('risk_tolerance', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16)),
                ('budget_style', models.CharField(blank=True, choices=[('strict', 'Strict'), ('flexible', 'Flexible'), ('optimize_value', 'Optimize value')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['financial_goal'], name='users_userp_financi_e8b889_idx'), models.Index(fields=['risk_tolerance'], name='users_userp_risk_to_55c218_idx'), models.Index(fields=['budget_style'], name='users_userp_budget__508361_idx')],
            },
        ),
    ]
