# Generated by Django 6.0.2 on 2026-02-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_remove_userprofile_id_alter_userpreference_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserComputed",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="computed",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("spending_personality", models.CharField(blank=True, max_length=64)),
                ("product_spending_style", models.CharField(blank=True, max_length=16)),
                (
                    "subscription_behavior_type",
                    models.CharField(blank=True, max_length=32),
                ),
                ("cost_weight", models.FloatField(blank=True, null=True)),
                ("quality_weight", models.FloatField(blank=True, null=True)),
                ("sustainability_weight", models.FloatField(blank=True, null=True)),
                (
                    "impulse_susceptibility_score",
                    models.FloatField(blank=True, null=True),
                ),
                ("regret_sensitivity", models.FloatField(blank=True, null=True)),
                ("budget_adherence_score", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRawExplicit",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="raw_explicit",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=64)),
                ("dob", models.DateField(blank=True, null=True)),
                ("age_range", models.CharField(blank=True, max_length=32)),
                (
                    "household_size",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("location_zip", models.CharField(blank=True, max_length=16)),
                ("life_stage", models.CharField(blank=True, max_length=32)),
                ("employment_type", models.CharField(blank=True, max_length=32)),
                (
                    "dependents_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("income_range", models.CharField(blank=True, max_length=32)),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_fixed_expenses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "financial_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("save_more", "Save more"),
                            ("invest", "Invest"),
                            ("reduce_debt", "Reduce debt"),
                            ("build_credit", "Build credit"),
                            ("control_subs", "Control subscriptions"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "risk_tolerance",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "budget_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("strict", "Strict"),
                            ("flexible", "Flexible"),
                            ("optimize_value", "Optimize value"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "value_priority_cost",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "value_priority_quality",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "value_priority_sustainability",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "self_report_research_habit",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRawInferred",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="raw_inferred",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("window_days", models.PositiveSmallIntegerField(default=90)),
                (
                    "avg_purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "purchase_price_variance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "category_distribution_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "percent_impulsive_purchases",
                    models.FloatField(blank=True, null=True),
                ),
                ("regret_frequency", models.FloatField(blank=True, null=True)),
                ("brand_repetition_rate", models.FloatField(blank=True, null=True)),
                (
                    "late_night_purchase_frequency",
                    models.FloatField(blank=True, null=True),
                ),
                ("avg_decision_time_minutes", models.FloatField(blank=True, null=True)),
                (
                    "active_subscriptions_count",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "total_subscription_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "percent_income_spent_on_subscriptions",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "subscription_usage_frequency_json",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "cancel_reactivation_frequency",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "actual_monthly_spending",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="users_userp_financi_e8b889_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="users_userp_risk_to_55c218_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="users_userp_budget__508361_idx",
        ),
        migrations.AlterUniqueTogether(
            name="userpreference",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="userpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="uniq_user_preference_key"
            ),
        ),
        migrations.AddIndex(
            model_name="usercomputed",
            index=models.Index(
                fields=["spending_personality"], name="users_userc_spendin_e710f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercomputed",
            index=models.Index(
                fields=["product_spending_style"], name="users_userc_product_6a9be1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercomputed",
            index=models.Index(
                fields=["subscription_behavior_type"],
                name="users_userc_subscri_1ba8e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userrawexplicit",
            index=models.Index(
                fields=["financial_goal"], name="users_userr_financi_f59914_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrawexplicit",
            index=models.Index(
                fields=["risk_tolerance"], name="users_userr_risk_to_a1d0ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrawexplicit",
            index=models.Index(
                fields=["budget_style"], name="users_userr_budget__3185e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrawexplicit",
            index=models.Index(
                fields=["income_range"], name="users_userr_income__3b05aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrawinferred",
            index=models.Index(
                fields=["window_days", "computed_at"],
                name="users_userr_window__c66ad9_idx",
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
