# Generated by Django 6.0.1 on 2026-04-01 03:18

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreference",
            name="value_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="age_range",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="budget_style",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("strict", "Strict"),
                    ("flexible", "Flexible"),
                    ("optimize_value", "Optimize value"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="dependents_count",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="display_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="dob",
            field=zapp.security.encrypted_fields.EncryptedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="employment_type",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="financial_goal",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("save_more", "Save more"),
                    ("invest", "Invest"),
                    ("reduce_debt", "Reduce debt"),
                    ("build_credit", "Build credit"),
                    ("control_subs", "Control subscriptions"),
                    ("other", "Other"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="household_size",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="income_range",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="life_stage",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="location_zip",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="monthly_fixed_expenses",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="monthly_income",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="risk_tolerance",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="self_report_research_habit",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="value_priority_cost",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="value_priority_quality",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawexplicit",
            name="value_priority_sustainability",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="active_subscriptions_count",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="actual_monthly_spending",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="avg_decision_time_minutes",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="avg_purchase_price",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="brand_repetition_rate",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="cancel_reactivation_frequency",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="category_distribution_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="late_night_purchase_frequency",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="percent_impulsive_purchases",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="percent_income_spent_on_subscriptions",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="purchase_price_variance",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="regret_frequency",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="subscription_usage_frequency_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="userrawinferred",
            name="total_subscription_cost",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
    ]
