# Generated by Django 6.0.1 on 2026-04-16 04:15

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_state_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrawinferred",
            name="data_sufficiency_tier",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True, default=""
            ),
        ),
    ]
