# Generated by Django 6.0.1 on 2026-03-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            (
                                "financial_data_access",
                                "Financial data access (Plaid / bank linking)",
                            )
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "policy_version",
                    models.CharField(
                        db_index=True,
                        help_text="Must match configured privacy policy version at acceptance time.",
                        max_length=64,
                    ),
                ),
                (
                    "consent_text_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hex of the exact consent text shown (optional but recommended).",
                        max_length=128,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="api", help_text="e.g. web, ios, android", max_length=32
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "consent_type", "policy_version"],
                        name="compliance__user_id_386eee_idx",
                    ),
                    models.Index(
                        fields=["user", "accepted_at"],
                        name="compliance__user_id_809d30_idx",
                    ),
                ],
            },
        ),
    ]
