# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_spotify_sync_idle_insights"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="spotifyconnection",
            name="integration_spotify_5e8802_idx",
        ),
        migrations.AlterField(
            model_name="spotifyconnection",
            name="spotify_user_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
