"""
Django settings for zapp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")


def _clean_env_url(value: str | None) -> str | None:
    if value is None:
        return None
    return value.strip().strip("'\"")


def _split_env_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = _split_env_csv(os.getenv("ALLOWED_HOSTS"))
AUTH_USER_MODEL = "users.User"

OPENAI_API_KEY = (os.getenv("OPENAI_API_KEY") or "").strip() or None
OPENAI_MODEL = (os.getenv("OPENAI_MODEL") or "gpt-4.1-mini").strip()
API_THROTTLE_ANON_RATE = (os.getenv("API_THROTTLE_ANON_RATE") or "30/minute").strip()
API_THROTTLE_USER_RATE = (os.getenv("API_THROTTLE_USER_RATE") or "120/minute").strip()
API_THROTTLE_AI_RATE = (os.getenv("API_THROTTLE_AI_RATE") or "20/minute").strip()
API_THROTTLE_AUDIT_INGEST_RATE = (os.getenv("API_THROTTLE_AUDIT_INGEST_RATE") or "120/minute").strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    "rest_framework",
    "corsheaders",
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'ai',
    'subscriptions',
    'valuations',
    'transactions',
    'banking',
    'compliance',
    'gamification',
    'integrations.apps.IntegrationsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=_clean_env_url(os.environ.get("DATABASE_URL")),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "users.supabase_auth.SupabaseJWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": (
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": API_THROTTLE_ANON_RATE,
        "user": API_THROTTLE_USER_RATE,
        "ai": API_THROTTLE_AI_RATE,
        "audit_ingest": API_THROTTLE_AUDIT_INGEST_RATE,
        # Banking / compliance: per-user; tune per environment
        "banking_sensitive": os.getenv("THROTTLE_BANKING_SENSITIVE", "120/hour"),
        "banking_link_token": os.getenv("THROTTLE_BANKING_LINK_TOKEN", "30/hour"),
        "compliance_consent": os.getenv("THROTTLE_COMPLIANCE_CONSENT", "60/hour"),
        "integrations_spotify": os.getenv("THROTTLE_INTEGRATIONS_SPOTIFY", "60/hour"),
    },
}

# --- Session / CSRF (browser BFF; explicit defaults) ---
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(60 * 60 * 24 * 14)))
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False

# Require MFA-backed AAL2 before a first-party session is treated as fully signed in.
AUTH_REQUIRE_AAL2 = os.getenv("AUTH_REQUIRE_AAL2", "true").lower() in (
    "1",
    "true",
    "yes",
)

# --- Banking step-up freshness (session-backed assurance) ---
BANKING_STEP_UP_REQUIRED = os.getenv("BANKING_STEP_UP_REQUIRED", "true").lower() in (
    "1",
    "true",
    "yes",
)
BANKING_STEP_UP_FRESHNESS_SECONDS = int(
    os.getenv("BANKING_STEP_UP_FRESHNESS_SECONDS", "900")
)

# Optional: Supabase service role for future admin ops (not required for password/OAuth BFF)
SUPABASE_SERVICE_ROLE_KEY = (os.getenv("SUPABASE_SERVICE_ROLE_KEY") or "").strip() or None

# OAuth BFF: redirect must match Supabase Dashboard > Auth > URL Configuration
SUPABASE_OAUTH_REDIRECT_URI = (os.getenv("SUPABASE_OAUTH_REDIRECT_URI") or "").strip() or None
# Optional backend callback for email confirmations. When set, signup passes this
# URL to Supabase, and the callback creates the server session before redirecting.
SUPABASE_EMAIL_CONFIRM_CALLBACK_URI = (
    os.getenv("SUPABASE_EMAIL_CONFIRM_CALLBACK_URI") or ""
).strip() or None
# Signup email confirmation link target (usually frontend onboarding route).
SUPABASE_EMAIL_CONFIRM_REDIRECT_TO = (
    os.getenv("SUPABASE_EMAIL_CONFIRM_REDIRECT_TO") or ""
).strip() or None
# Optional destination that onboarding should navigate to after completion.
ONBOARDING_AFTER_COMPLETE_REDIRECT_TO = (
    os.getenv("ONBOARDING_AFTER_COMPLETE_REDIRECT_TO") or ""
).strip() or None


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Plaid (bank connectivity)
PLAID_CLIENT_ID = os.getenv("PLAID_CLIENT_ID")
PLAID_SECRET = os.getenv("PLAID_SECRET")
PLAID_ENV = os.getenv("PLAID_ENV", "sandbox")
PLAID_PRODUCTS = os.getenv("PLAID_PRODUCTS", "transactions")
PLAID_COUNTRY_CODES = os.getenv("PLAID_COUNTRY_CODES", "US")
PLAID_WEBHOOK_URL = os.getenv("PLAID_WEBHOOK_URL", "")
PLAID_REDIRECT_URI = os.getenv("PLAID_REDIRECT_URI", "")
PLAID_CLIENT_NAME = os.getenv("PLAID_CLIENT_NAME", "Zapp")

# Supabase (JWT auth)
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_JWT_AUD = os.getenv("SUPABASE_JWT_AUD", "authenticated")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_JWT_ISS = os.getenv("SUPABASE_JWT_ISS")
SUPABASE_JWT_SECRET = os.getenv("SUPABASE_JWT_SECRET")  # For HS256 fallback (older Supabase projects)
SUPABASE_JWKS_CACHE_TTL_SECONDS = int(os.getenv("SUPABASE_JWKS_CACHE_TTL_SECONDS", "300"))

# --- Privacy policy (hosted document; version drives consent validity) ---
PRIVACY_POLICY_URL = os.getenv("PRIVACY_POLICY_URL", "")
PRIVACY_POLICY_VERSION = os.getenv("PRIVACY_POLICY_VERSION", "1.0.0")
PRIVACY_POLICY_EFFECTIVE_DATE = os.getenv("PRIVACY_POLICY_EFFECTIVE_DATE", "")

# --- Banking security policy (overridden in development/production) ---
BANKING_REQUIRE_MFA = os.getenv("BANKING_REQUIRE_MFA", "false").lower() in (
    "1",
    "true",
    "yes",
)
BANKING_REQUIRE_FINANCIAL_CONSENT = os.getenv(
    "BANKING_REQUIRE_FINANCIAL_CONSENT", "true"
).lower() in ("1", "true", "yes")

# Optional Fernet key (urlsafe base64) for app-layer encryption of Plaid access tokens at rest.
# Generate: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
PLAID_TOKEN_ENCRYPTION_KEY = os.getenv("PLAID_TOKEN_ENCRYPTION_KEY", "")
# Optional rotation list. First key is used for new writes; remaining keys are accepted for decrypt.
PLAID_TOKEN_ENCRYPTION_KEYS = os.getenv("PLAID_TOKEN_ENCRYPTION_KEYS", "")

# Optional Fernet key(s) for app data encrypted fields at rest.
APP_DATA_ENCRYPTION_KEY = os.getenv("APP_DATA_ENCRYPTION_KEY", "")
APP_DATA_ENCRYPTION_KEYS = os.getenv("APP_DATA_ENCRYPTION_KEYS", "")

# Spotify (category integration — OAuth + Web API)
SPOTIFY_CLIENT_ID = os.getenv("SPOTIFY_CLIENT_ID", "")
SPOTIFY_CLIENT_SECRET = os.getenv("SPOTIFY_CLIENT_SECRET", "")
SPOTIFY_REDIRECT_URI = os.getenv("SPOTIFY_REDIRECT_URI", "")
# Browser redirect after successful OAuth (e.g. https://app.example.com/settings/integrations)
SPOTIFY_OAUTH_SUCCESS_REDIRECT_URL = os.getenv("SPOTIFY_OAUTH_SUCCESS_REDIRECT_URL", "")
# Optional: dedicated Fernet key; falls back to PLAID_TOKEN_ENCRYPTION_KEY then plaintext
SPOTIFY_TOKEN_ENCRYPTION_KEY = os.getenv("SPOTIFY_TOKEN_ENCRYPTION_KEY", "")
SPOTIFY_DEFAULT_MONTHLY_PRICE_USD = os.getenv("SPOTIFY_DEFAULT_MONTHLY_PRICE_USD", "10.99")
SPOTIFY_AUTO_CREATE_SUBSCRIPTION = os.getenv(
    "SPOTIFY_AUTO_CREATE_SUBSCRIPTION", "true"
).lower() in ("1", "true", "yes")
# Run initial data sync in OAuth callback (sets last_synced_at; disable if redirect is too slow)
SPOTIFY_SYNC_ON_CONNECT = os.getenv(
    "SPOTIFY_SYNC_ON_CONNECT", "true"
).lower() in ("1", "true", "yes")

# Retention hints (operational; actual deletion uses management commands / legal process)
BANKING_DATA_RETENTION_DAYS_AFTER_DISCONNECT = int(
    os.getenv("BANKING_DATA_RETENTION_DAYS_AFTER_DISCONNECT", "0")
)
