"""
Django settings for zapp project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")


def _clean_env_url(value: str | None) -> str | None:
    if value is None:
        return None
    return value.strip().strip("'\"")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set")

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = []
AUTH_USER_MODEL = "users.User"

OPENAI_API_KEY = (os.getenv("OPENAI_API_KEY") or "").strip() or None
OPENAI_MODEL = (os.getenv("OPENAI_MODEL") or "gpt-4.1-mini").strip()
API_THROTTLE_ANON_RATE = (os.getenv("API_THROTTLE_ANON_RATE") or "30/minute").strip()
API_THROTTLE_USER_RATE = (os.getenv("API_THROTTLE_USER_RATE") or "120/minute").strip()
API_THROTTLE_AI_RATE = (os.getenv("API_THROTTLE_AI_RATE") or "20/minute").strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    "rest_framework",
    "corsheaders",
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'ai',
    'subscriptions',
    'valuations',
    'transactions',
    'banking',
    'compliance',
    'gamification',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=_clean_env_url(os.environ.get("DATABASE_URL")),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "users.supabase_auth.SupabaseJWTAuthentication",
    ),
    "DEFAULT_THROTTLE_RATES": {
        # Banking / compliance: per-user; tune per environment
        "banking_sensitive": os.getenv("THROTTLE_BANKING_SENSITIVE", "120/hour"),
        "banking_link_token": os.getenv("THROTTLE_BANKING_LINK_TOKEN", "30/hour"),
        "compliance_consent": os.getenv("THROTTLE_COMPLIANCE_CONSENT", "60/hour"),
    },
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Plaid (bank connectivity)
PLAID_CLIENT_ID = os.getenv("PLAID_CLIENT_ID")
PLAID_SECRET = os.getenv("PLAID_SECRET")
PLAID_ENV = os.getenv("PLAID_ENV", "sandbox")
PLAID_PRODUCTS = os.getenv("PLAID_PRODUCTS", "transactions")
PLAID_COUNTRY_CODES = os.getenv("PLAID_COUNTRY_CODES", "US")
PLAID_WEBHOOK_URL = os.getenv("PLAID_WEBHOOK_URL", "")
PLAID_REDIRECT_URI = os.getenv("PLAID_REDIRECT_URI", "")
PLAID_CLIENT_NAME = os.getenv("PLAID_CLIENT_NAME", "Zapp")

# Supabase (JWT auth)
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_JWT_AUD = os.getenv("SUPABASE_JWT_AUD", "authenticated")
SUPABASE_ANON_KEY = os.getenv("SUPABASE_ANON_KEY")
SUPABASE_JWT_ISS = os.getenv("SUPABASE_JWT_ISS")
SUPABASE_JWT_SECRET = os.getenv("SUPABASE_JWT_SECRET")  # For HS256 fallback (older Supabase projects)
SUPABASE_JWKS_CACHE_TTL_SECONDS = int(os.getenv("SUPABASE_JWKS_CACHE_TTL_SECONDS", "300"))

# --- Privacy policy (hosted document; version drives consent validity) ---
PRIVACY_POLICY_URL = os.getenv("PRIVACY_POLICY_URL", "")
PRIVACY_POLICY_VERSION = os.getenv("PRIVACY_POLICY_VERSION", "1.0.0")
PRIVACY_POLICY_EFFECTIVE_DATE = os.getenv("PRIVACY_POLICY_EFFECTIVE_DATE", "")

# --- Banking security policy (overridden in development/production) ---
BANKING_REQUIRE_MFA = os.getenv("BANKING_REQUIRE_MFA", "false").lower() in (
    "1",
    "true",
    "yes",
)
BANKING_REQUIRE_FINANCIAL_CONSENT = os.getenv(
    "BANKING_REQUIRE_FINANCIAL_CONSENT", "true"
).lower() in ("1", "true", "yes")

# Optional Fernet key (urlsafe base64) for app-layer encryption of Plaid access tokens at rest.
# Generate: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
PLAID_TOKEN_ENCRYPTION_KEY = os.getenv("PLAID_TOKEN_ENCRYPTION_KEY", "")

# Retention hints (operational; actual deletion uses management commands / legal process)
BANKING_DATA_RETENTION_DAYS_AFTER_DISCONNECT = int(
    os.getenv("BANKING_DATA_RETENTION_DAYS_AFTER_DISCONNECT", "0")
)
