# Generated by Django 6.0.2 on 2026-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0003_add_context_recommendation_evidence_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="itemvaluation",
            new_name="valuations__recomme_7a0353_idx",
            old_name="valuations_item_recommendation_idx",
        ),
        migrations.RenameIndex(
            model_name="subscriptionvaluation",
            new_name="valuations__recomme_c242f5_idx",
            old_name="valuations_subscription_recommendation_idx",
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="estimated_fair_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Market-based fair price estimate",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="personal_value_score",
            field=models.PositiveSmallIntegerField(
                help_text="0-100 personalized fit score for this user"
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="reasoning_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="UI-friendly reasoning: pros, cons, alternatives",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="explanation_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="UI-friendly explanation: summary, drivers, pros/cons",
            ),
        ),
        migrations.AlterField(
            model_name="valuationmodelversion",
            name="description",
            field=models.TextField(
                blank=True, help_text="What changed in this version", null=True
            ),
        ),
    ]
