# Generated by Django 6.0.1 on 2026-04-16 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0010_transaction_valuation_and_dirty_state"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transactionvaluation",
            new_name="valuations__user_id_b0becb_idx",
            old_name="valuations_t_user_id_5d358e_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionvaluation",
            new_name="valuations__transac_ef172e_idx",
            old_name="valuations_t_transac_61d822_idx",
        ),
        migrations.RenameIndex(
            model_name="transactionvaluation",
            new_name="valuations__model_v_1ebdf3_idx",
            old_name="valuations_t_model_v_27a80e_idx",
        ),
        migrations.RenameIndex(
            model_name="valuationdirtystate",
            new_name="valuations__priorit_270373_idx",
            old_name="valuations_v_priority_17c7c8_idx",
        ),
        migrations.RenameIndex(
            model_name="valuationdirtystate",
            new_name="valuations__user_id_c598d5_idx",
            old_name="valuations_v_user_id_733629_idx",
        ),
    ]
