# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "valuations",
            "0011_rename_valuations_t_user_id_5d358e_idx_valuations__user_id_b0becb_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="valuationmodelversion",
            name="valuations__name_9fb73c_idx",
        ),
    ]
