# Generated by Codex on 2026-03-11

from django.db import migrations


BADGE_CATALOG = [
    ("first_purchase", "First Purchase Logged", "Log your first purchase in Zapp.", "receipt", "purchase"),
    ("purchase_5", "5 Purchases Logged", "Log 5 purchases.", "receipt-stack", "purchase"),
    ("purchase_25", "25 Purchases Logged", "Log 25 purchases.", "ledger", "purchase"),
    ("purchase_100", "100 Purchases Logged", "Log 100 purchases.", "archive", "purchase"),
    ("first_reflection", "First Reflection", "Complete your first purchase reflection.", "spark", "reflection"),
    ("reflection_5", "5 Reflections", "Complete 5 purchase reflections.", "spark-burst", "reflection"),
    ("reflection_20", "20 Reflections", "Complete 20 purchase reflections.", "journal", "reflection"),
    ("first_same_day_reflection", "Same-Day Insight", "Reflect on a purchase the same day you made it.", "clock-check", "reflection"),
    ("same_day_reflection_7", "7 Same-Day Reflections", "Complete 7 same-day reflections.", "calendar-check", "reflection"),
    ("first_advisor_use", "Advisor Activated", "Use Zapp's advisor before making a purchase.", "advisor", "advisor"),
    ("item_valuation_5", "5 Item Valuations", "Run 5 item valuations.", "scale", "advisor"),
    ("item_valuation_20", "20 Item Valuations", "Run 20 item valuations.", "scale-stack", "advisor"),
    ("first_subscription_added", "First Subscription Tracked", "Track your first subscription.", "card-plus", "subscription"),
    ("subscription_added_5", "5 Subscriptions Tracked", "Track 5 subscriptions.", "cards", "subscription"),
    ("first_subscription_cleanup", "Subscription Cleanup", "Cancel or pause a subscription.", "broom", "subscription"),
    ("joined_group", "Joined a Group", "Join your first accountability group.", "users", "social"),
    ("created_group", "Created a Group", "Create your first accountability group.", "user-plus", "social"),
    ("streak_7", "7-Day Streak", "Maintain a 7-day streak.", "flame", "streak"),
    ("streak_14", "14-Day Streak", "Maintain a 14-day streak.", "flame-double", "streak"),
    ("streak_30", "30-Day Streak", "Maintain a 30-day streak.", "flame-trophy", "streak"),
]


def seed_badges(apps, schema_editor):
    Badge = apps.get_model("gamification", "Badge")
    for code, name, description, icon, category in BADGE_CATALOG:
        Badge.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "description": description,
                "icon": icon,
                "category": category,
                "is_active": True,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_badges, noop),
    ]
