# Generated by Django 6.0.1 on 2026-03-11 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0003_groupinvite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="category",
            field=models.CharField(
                choices=[
                    ("onboarding", "Onboarding"),
                    ("transactions", "Transactions"),
                    ("reflections", "Reflections"),
                    ("advisor", "Advisor"),
                    ("subscriptions", "Subscriptions"),
                    ("social", "Social"),
                    ("streaks", "Streaks"),
                    ("monthly_goals", "Monthly goals"),
                    ("improvement", "Improvement"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="groupinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="pointevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("log_purchase", "Log purchase"),
                    ("log_purchase_new_day", "Log purchase on a new day"),
                    ("reflect_same_day", "Reflect same day"),
                    ("reflect_risky_purchase", "Reflect on risky purchase"),
                    ("use_advisor", "Use advisor"),
                    ("first_advisor_use", "First advisor use"),
                    ("weekly_review", "Complete weekly review"),
                    ("add_subscription", "Add subscription"),
                    ("cancel_subscription", "Cancel subscription"),
                    ("pause_subscription", "Pause subscription"),
                    ("complete_onboarding", "Complete onboarding"),
                    ("set_monthly_target", "Set monthly target"),
                    ("complete_monthly_target", "Complete monthly target"),
                    ("complete_monthly_review", "Complete monthly review"),
                    ("review_upcoming_renewal", "Review upcoming renewal"),
                    ("complete_subscription_audit", "Complete subscription audit"),
                    ("run_subscription_valuation", "Run subscription valuation"),
                    ("run_item_valuation", "Run item valuation"),
                    (
                        "follow_wait_recommendation",
                        "Follow wait or skip recommendation",
                    ),
                    ("join_group", "Join group"),
                    ("create_group", "Create group"),
                    ("leaderboard_top_three", "Finish in weekly top 3"),
                    ("leaderboard_winner", "Finish first in weekly leaderboard"),
                    ("streak_7_bonus", "7-day streak bonus"),
                    ("streak_14_bonus", "14-day streak bonus"),
                    ("streak_30_bonus", "30-day streak bonus"),
                ],
                max_length=48,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyTarget",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target_type", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=128)),
                ("month_start", models.DateField()),
                ("target_value", models.PositiveIntegerField()),
                ("current_value", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "month_start", "status"],
                        name="gamificatio_user_id_959a7b_idx",
                    ),
                    models.Index(
                        fields=["target_type", "month_start"],
                        name="gamificatio_target__fdfd69_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "target_type", "month_start"),
                        name="uniq_user_target_month",
                    )
                ],
            },
        ),
    ]
