# Generated by Django 6.0.1 on 2026-04-01 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0006_userstreak_total_points_earned"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicReview",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "review_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("completed", "Completed")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "review_type", "period_start"],
                        name="gamificatio_user_id_52c3f3_idx",
                    ),
                    models.Index(
                        fields=["user", "review_type", "status"],
                        name="gamificatio_user_id_11eb47_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="gamificatio_period__dbf8a7_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "review_type", "period_start"),
                        name="uniq_user_periodic_review",
                    )
                ],
            },
        ),
    ]
