# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gamification", "0007_periodicreview"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="badge",
            name="gamificatio_code_edd252_idx",
        ),
        migrations.RemoveIndex(
            model_name="group",
            name="gamificatio_invite__7654b3_idx",
        ),
        migrations.RemoveIndex(
            model_name="groupinvite",
            name="gamificatio_invite__daf920_idx",
        ),
        migrations.RemoveIndex(
            model_name="periodicreview",
            name="gamificatio_user_id_52c3f3_idx",
        ),
        migrations.RemoveIndex(
            model_name="pointevent",
            name="gamificatio_event_k_b535f9_idx",
        ),
    ]
