from .models import BadgeCategory, PointAction


BADGE_CATALOG = [
    {
        "code": "first_purchase",
        "name": "First Purchase Logged",
        "description": "Log your first purchase in Zapp.",
        "icon": "receipt",
        "category": BadgeCategory.PURCHASE,
    },
    {
        "code": "purchase_5",
        "name": "5 Purchases Logged",
        "description": "Log 5 purchases.",
        "icon": "receipt-stack",
        "category": BadgeCategory.PURCHASE,
    },
    {
        "code": "purchase_25",
        "name": "25 Purchases Logged",
        "description": "Log 25 purchases.",
        "icon": "ledger",
        "category": BadgeCategory.PURCHASE,
    },
    {
        "code": "purchase_100",
        "name": "100 Purchases Logged",
        "description": "Log 100 purchases.",
        "icon": "archive",
        "category": BadgeCategory.PURCHASE,
    },
    {
        "code": "first_reflection",
        "name": "First Reflection",
        "description": "Complete your first purchase reflection.",
        "icon": "spark",
        "category": BadgeCategory.REFLECTION,
    },
    {
        "code": "reflection_5",
        "name": "5 Reflections",
        "description": "Complete 5 purchase reflections.",
        "icon": "spark-burst",
        "category": BadgeCategory.REFLECTION,
    },
    {
        "code": "reflection_20",
        "name": "20 Reflections",
        "description": "Complete 20 purchase reflections.",
        "icon": "journal",
        "category": BadgeCategory.REFLECTION,
    },
    {
        "code": "first_same_day_reflection",
        "name": "Same-Day Insight",
        "description": "Reflect on a purchase the same day you made it.",
        "icon": "clock-check",
        "category": BadgeCategory.REFLECTION,
    },
    {
        "code": "same_day_reflection_7",
        "name": "7 Same-Day Reflections",
        "description": "Complete 7 same-day reflections.",
        "icon": "calendar-check",
        "category": BadgeCategory.REFLECTION,
    },
    {
        "code": "first_advisor_use",
        "name": "Advisor Activated",
        "description": "Use Zapp's advisor before making a purchase.",
        "icon": "advisor",
        "category": BadgeCategory.ADVISOR,
    },
    {
        "code": "item_valuation_5",
        "name": "5 Item Valuations",
        "description": "Run 5 item valuations.",
        "icon": "scale",
        "category": BadgeCategory.ADVISOR,
    },
    {
        "code": "item_valuation_20",
        "name": "20 Item Valuations",
        "description": "Run 20 item valuations.",
        "icon": "scale-stack",
        "category": BadgeCategory.ADVISOR,
    },
    {
        "code": "first_subscription_added",
        "name": "First Subscription Tracked",
        "description": "Track your first subscription.",
        "icon": "card-plus",
        "category": BadgeCategory.SUBSCRIPTION,
    },
    {
        "code": "subscription_added_5",
        "name": "5 Subscriptions Tracked",
        "description": "Track 5 subscriptions.",
        "icon": "cards",
        "category": BadgeCategory.SUBSCRIPTION,
    },
    {
        "code": "first_subscription_cleanup",
        "name": "Subscription Cleanup",
        "description": "Cancel or pause a subscription.",
        "icon": "broom",
        "category": BadgeCategory.SUBSCRIPTION,
    },
    {
        "code": "joined_group",
        "name": "Joined a Group",
        "description": "Join your first accountability group.",
        "icon": "users",
        "category": BadgeCategory.SOCIAL,
    },
    {
        "code": "created_group",
        "name": "Created a Group",
        "description": "Create your first accountability group.",
        "icon": "user-plus",
        "category": BadgeCategory.SOCIAL,
    },
    {
        "code": "streak_7",
        "name": "7-Day Streak",
        "description": "Maintain a 7-day streak.",
        "icon": "flame",
        "category": BadgeCategory.STREAK,
    },
    {
        "code": "streak_14",
        "name": "14-Day Streak",
        "description": "Maintain a 14-day streak.",
        "icon": "flame-double",
        "category": BadgeCategory.STREAK,
    },
    {
        "code": "streak_30",
        "name": "30-Day Streak",
        "description": "Maintain a 30-day streak.",
        "icon": "flame-trophy",
        "category": BadgeCategory.STREAK,
    },
]


ACTION_POINTS = {
    PointAction.LOG_PURCHASE: 10,
    PointAction.REFLECT_SAME_DAY: 15,
    PointAction.USE_ADVISOR: 12,
    PointAction.WEEKLY_REVIEW: 20,
    PointAction.ADD_SUBSCRIPTION: 10,
    PointAction.CANCEL_SUBSCRIPTION: 15,
    PointAction.PAUSE_SUBSCRIPTION: 12,
    PointAction.COMPLETE_ONBOARDING: 20,
    PointAction.SET_MONTHLY_TARGET: 10,
    PointAction.COMPLETE_MONTHLY_TARGET: 30,
    PointAction.COMPLETE_MONTHLY_REVIEW: 20,
    PointAction.RUN_SUBSCRIPTION_VALUATION: 10,
    PointAction.RUN_ITEM_VALUATION: 10,
    PointAction.JOIN_GROUP: 5,
    PointAction.CREATE_GROUP: 10,
}
