from .models import BadgeCategory, PointAction


BADGE_CATALOG = [
    {"code": "first_step", "name": "First Step", "description": "Completed onboarding.", "icon": "spark", "category": BadgeCategory.ONBOARDING},
    {"code": "goal_setter", "name": "Goal Setter", "description": "Created a first monthly target.", "icon": "target", "category": BadgeCategory.MONTHLY_GOALS},
    {"code": "group_ready", "name": "Group Ready", "description": "Joined a group.", "icon": "users", "category": BadgeCategory.SOCIAL},
    {"code": "founder", "name": "Founder", "description": "Created a group.", "icon": "user-plus", "category": BadgeCategory.SOCIAL},
    {"code": "first_log", "name": "First Log", "description": "Logged the first transaction.", "icon": "receipt", "category": BadgeCategory.TRANSACTIONS},
    {"code": "money_tracker_1", "name": "Money Tracker I", "description": "Logged 5 transactions.", "icon": "receipt-stack", "category": BadgeCategory.TRANSACTIONS},
    {"code": "money_tracker_2", "name": "Money Tracker II", "description": "Logged 25 transactions.", "icon": "ledger", "category": BadgeCategory.TRANSACTIONS},
    {"code": "money_tracker_3", "name": "Money Tracker III", "description": "Logged 100 transactions.", "icon": "archive", "category": BadgeCategory.TRANSACTIONS},
    {"code": "category_explorer", "name": "Category Explorer", "description": "Logged across multiple spending categories.", "icon": "compass", "category": BadgeCategory.TRANSACTIONS},
    {"code": "consistent_logger", "name": "Consistent Logger", "description": "Logged activity across 7 active days.", "icon": "calendar", "category": BadgeCategory.TRANSACTIONS},
    {"code": "honest_check_in", "name": "Honest Check-In", "description": "Completed the first reflection.", "icon": "spark", "category": BadgeCategory.REFLECTIONS},
    {"code": "same_day_thinker", "name": "Same-Day Thinker", "description": "Completed the first same-day reflection.", "icon": "clock-check", "category": BadgeCategory.REFLECTIONS},
    {"code": "reflection_rookie", "name": "Reflection Rookie", "description": "Completed 5 reflections.", "icon": "journal", "category": BadgeCategory.REFLECTIONS},
    {"code": "reflection_habit", "name": "Reflection Habit", "description": "Completed 20 reflections.", "icon": "journal-stack", "category": BadgeCategory.REFLECTIONS},
    {"code": "no_regret_zone", "name": "No-Regret Zone", "description": "Completed 7 same-day reflections.", "icon": "shield", "category": BadgeCategory.REFLECTIONS},
    {"code": "mindful_buyer", "name": "Mindful Buyer", "description": "Completed 15 same-day reflections.", "icon": "brain", "category": BadgeCategory.REFLECTIONS},
    {"code": "pause_and_think", "name": "Pause and Think", "description": "Repeatedly reflected on risky purchases.", "icon": "pause", "category": BadgeCategory.IMPROVEMENT},
    {"code": "advisor_curious", "name": "Advisor Curious", "description": "Used the advisor for the first time.", "icon": "advisor", "category": BadgeCategory.ADVISOR},
    {"code": "smart_shopper", "name": "Smart Shopper", "description": "Completed 5 item valuations.", "icon": "scale", "category": BadgeCategory.ADVISOR},
    {"code": "value_checker", "name": "Value Checker", "description": "Completed 20 item valuations.", "icon": "scale-stack", "category": BadgeCategory.ADVISOR},
    {"code": "price_detective", "name": "Price Detective", "description": "Checked value across multiple products.", "icon": "search", "category": BadgeCategory.ADVISOR},
    {"code": "wait_warrior", "name": "Wait Warrior", "description": "Followed multiple wait or skip recommendations.", "icon": "hourglass", "category": BadgeCategory.ADVISOR},
    {"code": "alternative_hunter", "name": "Alternative Hunter", "description": "Consistently checked alternatives.", "icon": "shuffle", "category": BadgeCategory.ADVISOR},
    {"code": "subscription_starter", "name": "Subscription Starter", "description": "Added the first subscription.", "icon": "card-plus", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "subscription_mapper", "name": "Subscription Mapper", "description": "Tracked 5 subscriptions.", "icon": "cards", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "cleanup_crew", "name": "Cleanup Crew", "description": "Paused or cancelled a subscription.", "icon": "broom", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "renewal_ready", "name": "Renewal Ready", "description": "Reviewed an upcoming renewal.", "icon": "bell", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "subscription_auditor", "name": "Subscription Auditor", "description": "Completed a subscription audit.", "icon": "clipboard", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "leak_plugger", "name": "Leak Plugger", "description": "Reduced unnecessary recurring spend.", "icon": "wrench", "category": BadgeCategory.SUBSCRIPTIONS},
    {"code": "getting_started", "name": "Getting Started", "description": "Reached a 3-day streak.", "icon": "flame", "category": BadgeCategory.STREAKS},
    {"code": "locked_in", "name": "Locked In", "description": "Reached a 7-day streak.", "icon": "flame", "category": BadgeCategory.STREAKS},
    {"code": "habit_builder", "name": "Habit Builder", "description": "Reached a 14-day streak.", "icon": "flame-double", "category": BadgeCategory.STREAKS},
    {"code": "unstoppable", "name": "Unstoppable", "description": "Reached a 30-day streak.", "icon": "flame-trophy", "category": BadgeCategory.STREAKS},
    {"code": "iron_discipline", "name": "Iron Discipline", "description": "Reached a 60-day streak.", "icon": "anvil", "category": BadgeCategory.STREAKS},
    {"code": "friendly_rival", "name": "Friendly Rival", "description": "Participated in a weekly leaderboard.", "icon": "users", "category": BadgeCategory.SOCIAL},
    {"code": "podium_finish", "name": "Podium Finish", "description": "Finished in the weekly top 3.", "icon": "medal", "category": BadgeCategory.SOCIAL},
    {"code": "weekly_winner", "name": "Weekly Winner", "description": "Finished first in the weekly leaderboard.", "icon": "trophy", "category": BadgeCategory.SOCIAL},
    {"code": "comeback_kid", "name": "Comeback Kid", "description": "Improved rank significantly over time.", "icon": "arrow-up", "category": BadgeCategory.SOCIAL},
    {"code": "monthly_momentum", "name": "Monthly Momentum", "description": "Hit a monthly target.", "icon": "target", "category": BadgeCategory.MONTHLY_GOALS},
    {"code": "target_taker", "name": "Target Taker", "description": "Hit 3 monthly targets.", "icon": "target-stack", "category": BadgeCategory.MONTHLY_GOALS},
    {"code": "month_master", "name": "Month Master", "description": "Completed all monthly targets.", "icon": "calendar-check", "category": BadgeCategory.MONTHLY_GOALS},
    {"code": "consistency_champ", "name": "Consistency Champ", "description": "Completed targets across multiple months.", "icon": "calendar-star", "category": BadgeCategory.MONTHLY_GOALS},
    {"code": "budget_keeper", "name": "Budget Keeper", "description": "Improved budget adherence.", "icon": "wallet", "category": BadgeCategory.IMPROVEMENT},
    {"code": "impulse_tamer", "name": "Impulse Tamer", "description": "Reduced impulsive purchase behavior.", "icon": "brake", "category": BadgeCategory.IMPROVEMENT},
    {"code": "regret_reducer", "name": "Regret Reducer", "description": "Lowered regret frequency.", "icon": "shield-check", "category": BadgeCategory.IMPROVEMENT},
    {"code": "value_maximizer", "name": "Value Maximizer", "description": "Improved value-based decision behavior.", "icon": "gem", "category": BadgeCategory.IMPROVEMENT},
    {"code": "subscription_strategist", "name": "Subscription Strategist", "description": "Improved subscription decision quality.", "icon": "strategy", "category": BadgeCategory.IMPROVEMENT},
]


ACTION_POINTS = {
    PointAction.COMPLETE_ONBOARDING: 20,
    PointAction.SET_MONTHLY_TARGET: 10,
    PointAction.JOIN_GROUP: 10,
    PointAction.CREATE_GROUP: 15,
    PointAction.LOG_PURCHASE: 5,
    PointAction.LOG_PURCHASE_NEW_DAY: 5,
    PointAction.STREAK_7_BONUS: 20,
    PointAction.STREAK_14_BONUS: 35,
    PointAction.STREAK_30_BONUS: 75,
    PointAction.REFLECT_SAME_DAY: 12,
    PointAction.REFLECT_RISKY_PURCHASE: 15,
    PointAction.WEEKLY_REVIEW: 20,
    PointAction.COMPLETE_MONTHLY_REVIEW: 35,
    PointAction.FIRST_ADVISOR_USE: 10,
    PointAction.RUN_ITEM_VALUATION: 8,
    PointAction.RUN_SUBSCRIPTION_VALUATION: 10,
    PointAction.USE_ADVISOR: 12,
    PointAction.FOLLOW_WAIT_RECOMMENDATION: 15,
    PointAction.ADD_SUBSCRIPTION: 8,
    PointAction.PAUSE_SUBSCRIPTION: 12,
    PointAction.CANCEL_SUBSCRIPTION: 15,
    PointAction.REVIEW_UPCOMING_RENEWAL: 10,
    PointAction.COMPLETE_SUBSCRIPTION_AUDIT: 25,
    PointAction.LEADERBOARD_TOP_THREE: 20,
    PointAction.LEADERBOARD_WINNER: 35,
    PointAction.COMPLETE_MONTHLY_TARGET: 35,
}
