# Generated by Django 6.0.1 on 2026-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_merchant_id_alter_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
