# Generated by Django 6.0.1 on 2026-02-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_merchant_id_alter_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='usage_frequency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Uses per week or your chosen unit', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='reactivation_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this subscription has been reactivated'),
        ),
    ]
