# Generated by Django 6.0.2 on 2026-03-12 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscription_usage_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="feedback_confidence",
            field=models.FloatField(
                blank=True,
                help_text="0-1 confidence in feedback_value_score",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="feedback_value_score",
            field=models.FloatField(
                blank=True,
                help_text="0-1 derived from reflection_text + ratings (user feedback on value)",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("feedback_value_score__gte", 0),
                        ("feedback_value_score__lte", 1),
                    ),
                    ("feedback_value_score__isnull", True),
                    _connector="OR",
                ),
                name="valid_subscription_feedback_value_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("feedback_confidence__gte", 0), ("feedback_confidence__lte", 1)
                    ),
                    ("feedback_confidence__isnull", True),
                    _connector="OR",
                ),
                name="valid_subscription_feedback_confidence",
            ),
        ),
    ]
