# Generated by Django 6.0.1 on 2026-04-08 23:49
#
# PostgreSQL/Supabase: run ALTER COLUMN outside Django's schema_editor transaction
# (autocommit cursor) so "pending trigger events" cannot block the type change.
# integrations.0001_initial runs after 0007 and before 0008 in the default graph;
# FK/constraint DDL on related tables can leave session state that breaks ALTER
# when executed through schema_editor.execute in the same connection semantics.
#
# State is updated via SeparateDatabaseAndState.state_operations only.
# Data backfill lives in 0009.

from django.conf import settings
from django.db import migrations, models

_PG_ALTER_FLOAT = (
    "ALTER TABLE subscriptions_subscription "
    "ALTER COLUMN usage_frequency TYPE double precision "
    "USING usage_frequency::double precision;"
)
_PG_ALTER_REVERSE = (
    "ALTER TABLE subscriptions_subscription "
    "ALTER COLUMN usage_frequency TYPE smallint "
    "USING CASE WHEN usage_frequency IS NULL THEN NULL "
    "ELSE LEAST(32767, GREATEST(0, round(usage_frequency)))::smallint END;"
)


def _pg_column_data_type(conn, table: str, column: str) -> str | None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT data_type
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = %s
              AND column_name = %s
            """,
            [table, column],
        )
        row = cursor.fetchone()
    return row[0] if row else None


def _pg_run_autocommit_sql(conn, sql: str) -> None:
    conn.ensure_connection()
    old = conn.get_autocommit()
    try:
        conn.set_autocommit(True)
        with conn.cursor() as cursor:
            cursor.execute(sql)
    finally:
        conn.set_autocommit(old)


def forward_usage_frequency(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        current_type = _pg_column_data_type(conn, "subscriptions_subscription", "usage_frequency")
        if current_type in {"text", "character varying"}:
            # Parallel migration path already moved usage_frequency to encrypted text storage.
            # Skip numeric ALTER in that case; merged migrations later normalize encrypted float state.
            return
        _pg_run_autocommit_sql(conn, _PG_ALTER_FLOAT)
        return

    Subscription = apps.get_model("subscriptions", "Subscription")
    from_field = Subscription._meta.get_field("usage_frequency")
    new_field = models.FloatField(
        blank=True,
        help_text="0-1 normalized usage intensity (e.g. Spotify: active listening days / 30).",
        null=True,
    )
    new_field.set_attributes_from_name(from_field.name)
    new_field.model = Subscription
    schema_editor.alter_field(Subscription, from_field, new_field)


def reverse_usage_frequency(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "postgresql":
        current_type = _pg_column_data_type(conn, "subscriptions_subscription", "usage_frequency")
        if current_type in {"text", "character varying"}:
            return
        _pg_run_autocommit_sql(conn, _PG_ALTER_REVERSE)
        return

    Subscription = apps.get_model("subscriptions", "Subscription")
    from_field = Subscription._meta.get_field("usage_frequency")
    new_field = models.PositiveSmallIntegerField(
        blank=True,
        help_text="Uses per week or your chosen unit",
        null=True,
    )
    new_field.set_attributes_from_name(from_field.name)
    new_field.model = Subscription
    schema_editor.alter_field(Subscription, from_field, new_field)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ("subscriptions", "0007_subscription_utilization_cost_benefit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    forward_usage_frequency,
                    reverse_usage_frequency,
                    atomic=False,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="subscription",
                    name="usage_frequency",
                    field=models.FloatField(
                        blank=True,
                        help_text="0-1 normalized usage intensity (e.g. Spotify: active listening days / 30).",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
