# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0012_alter_merchant_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="merchant",
            name="subscriptio_name_554356_idx",
        ),
    ]
