# Generated by Django 6.0.1 on 2026-03-31 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_security_compliance_plaid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("attempt", "Attempt"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("anonymous", "Anonymous"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("source_system", models.CharField(db_index=True, max_length=64)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("action", models.CharField(blank=True, max_length=64)),
                ("resource_type", models.CharField(blank=True, db_index=True, max_length=64)),
                ("resource_id", models.CharField(blank=True, max_length=128)),
                ("route", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=16)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="compliance__user_id_cc2933_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="compliance__resourc_05eb54_idx",
                    ),
                ],
            },
        ),
    ]
