# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "compliance",
            "0003_rename_compliance__user_id_cc2933_idx_compliance__user_id_dce5c2_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="actor_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("anonymous", "Anonymous"),
                    ("system", "System"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("attempt", "Attempt"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="request_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="resource_type",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="source_system",
            field=models.CharField(max_length=64),
        ),
    ]
