# Generated by Django 6.0.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankConnection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("plaid_item_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("plaid_access_token", models.CharField(max_length=512)),
                ("institution_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("institution_name", models.CharField(blank=True, max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("sync_cursor", models.TextField(blank=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("plaid_account_id", models.CharField(db_index=True, max_length=64)),
                ("name", models.CharField(max_length=256)),
                ("official_name", models.CharField(blank=True, max_length=256)),
                ("mask", models.CharField(blank=True, max_length=8)),
                ("type", models.CharField(blank=True, max_length=64)),
                ("subtype", models.CharField(blank=True, max_length=64)),
                (
                    "current_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "available_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("iso_currency_code", models.CharField(default="USD", max_length=3)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="banking.bankconnection",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("plaid_transaction_id", models.CharField(db_index=True, max_length=64)),
                ("pending_transaction_id", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=512)),
                ("merchant_name", models.CharField(blank=True, max_length=512)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("iso_currency_code", models.CharField(default="USD", max_length=3)),
                ("date", models.DateField()),
                ("authorized_date", models.DateField(blank=True, null=True)),
                ("pending", models.BooleanField(default=False)),
                (
                    "removed",
                    models.BooleanField(
                        default=False,
                        help_text="Soft-delete: transaction was removed in Plaid sync",
                    ),
                ),
                ("category_primary", models.CharField(blank=True, max_length=128)),
                ("category_detailed", models.CharField(blank=True, max_length=256)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.bankconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="bankconnection",
            index=models.Index(fields=["user", "status"], name="banking_ban_user_id_7a8f3d_idx"),
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(
                fields=("connection", "plaid_account_id"),
                name="uniq_connection_plaid_account",
            ),
        ),
        migrations.AddIndex(
            model_name="bankaccount",
            index=models.Index(
                fields=["connection", "plaid_account_id"],
                name="banking_ban_connect_9a2c4e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("connection", "plaid_transaction_id"),
                name="uniq_connection_plaid_transaction",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(fields=["user", "date"], name="banking_ban_user_id_2b8e1f_idx"),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(fields=["account", "date"], name="banking_ban_account_3c9d5e_idx"),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["user", "removed", "date"],
                name="banking_ban_user_id_4d7a2e_idx",
            ),
        ),
    ]
