# Generated by Django 6.0.1 on 2026-03-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0006_security_compliance_plaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankconnection",
            name="plaid_access_token",
            field=models.TextField(),
        ),
    ]
