# Generated by Django 6.0.1 on 2026-04-01 03:18

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0007_plaid_access_token_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="available_balance",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="current_balance",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="mask",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="name",
            field=zapp.security.encrypted_fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="official_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="raw_payload",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="bankconnection",
            name="institution_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="bankconnection",
            name="sync_cursor",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="amount",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="authorized_date",
            field=zapp.security.encrypted_fields.EncryptedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="category_detailed",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="category_primary",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="category_source",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Source of assigned category: plaid, merchant_override, zapp_mapping, user_override",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="merchant_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="name",
            field=zapp.security.encrypted_fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="raw_payload",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="user_override_category",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="User-assigned category; takes precedence over Zapp categories",
            ),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="zapp_subcategory",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                choices=[
                    ("groceries", "Groceries"),
                    ("household_supplies", "Household Supplies"),
                    ("toiletries", "Toiletries"),
                    ("pharmacy_essentials", "Pharmacy Essentials"),
                    ("coffee", "Coffee"),
                    ("takeout", "Takeout"),
                    ("fast_food", "Fast Food"),
                    ("restaurants", "Restaurants"),
                    ("delivery", "Delivery"),
                    ("snacks_dessert", "Snacks / Dessert"),
                    ("clothing", "Clothing"),
                    ("tech", "Tech"),
                    ("home_decor", "Home Decor"),
                    ("personal_items", "Personal Items"),
                    ("impulse_purchase", "Impulse Purchase"),
                    ("general", "General"),
                    ("electronics", "Electronics"),
                    ("streaming", "Streaming"),
                    ("music", "Music"),
                    ("software", "Software"),
                    ("productivity_tools", "Productivity Tools"),
                    ("software_productivity", "Software / Productivity"),
                    ("fitness_membership", "Fitness Membership"),
                    ("cloud_storage", "Cloud / Storage"),
                    ("games", "Games"),
                    ("nightlife", "Nightlife"),
                    ("events", "Events"),
                    ("hobbies", "Hobbies"),
                    ("movies", "Movies"),
                    ("sports", "Sports"),
                    ("live_events", "Live Events"),
                    ("theater", "Theater"),
                    ("ride_share", "Ride Share"),
                    ("gas", "Gas"),
                    ("parking", "Parking"),
                    ("public_transit", "Public Transit"),
                    ("car_rental", "Car Rental"),
                    ("tolls", "Tolls"),
                    ("flights", "Flights"),
                    ("hotels", "Hotels"),
                    ("airbnb", "Airbnb"),
                    ("vacation_packages", "Vacation Packages"),
                    ("rent", "Rent"),
                    ("electricity", "Electricity"),
                    ("internet", "Internet"),
                    ("phone", "Phone"),
                    ("insurance", "Insurance"),
                    ("doctor", "Doctor"),
                    ("dental", "Dental"),
                    ("therapy", "Therapy"),
                    ("medication", "Medication"),
                    ("savings_transfer", "Savings Transfer"),
                    ("credit_card_payment", "Credit Card Payment"),
                    ("peer_transfer", "Peer Transfer"),
                    ("investing_transfer", "Investing Transfer"),
                    ("atm_cash", "ATM / Cash Withdrawal"),
                    ("payroll", "Payroll"),
                ],
            ),
        ),
    ]
