# Generated by Django 6.0.1 on 2026-02-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='satisfaction_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1-10 scale: how satisfied with this purchase', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='regret_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100 scale: level of regret about this purchase', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='repurchase_likelihood',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0-100 scale: likelihood to buy again', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='usage_frequency',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How often user expects to use this (e.g., times per week)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reflection_text',
            field=models.TextField(blank=True, help_text="User's thoughts/notes about this purchase", null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='considered_at',
            field=models.DateTimeField(blank=True, help_text='When user started considering this purchase (for decision time calculation)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='used_buy_advisor',
            field=models.BooleanField(default=False, help_text='Did the user use the buy advisor flow for this purchase'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='self_report_researched',
            field=models.BooleanField(blank=True, help_text='Did user report researching before buying (nullable = not asked)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='impulse_score',
            field=models.FloatField(blank=True, help_text='0-1 computed impulse likelihood for this transaction', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='regret_score',
            field=models.FloatField(blank=True, help_text='0-1 computed regret likelihood for this transaction', null=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'regret_rating'], name='transaction_user_regret_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'satisfaction_rating'], name='transaction_user_satisfaction_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(
                condition=models.Q(('satisfaction_rating__gte', 1), ('satisfaction_rating__lte', 10)) | models.Q(('satisfaction_rating__isnull', True)),
                name='valid_satisfaction_rating',
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(
                condition=models.Q(('regret_rating__gte', 0), ('regret_rating__lte', 100)) | models.Q(('regret_rating__isnull', True)),
                name='valid_regret_rating',
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(
                condition=models.Q(('repurchase_likelihood__gte', 0), ('repurchase_likelihood__lte', 100)) | models.Q(('repurchase_likelihood__isnull', True)),
                name='valid_repurchase_likelihood',
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(
                condition=models.Q(('impulse_score__gte', 0), ('impulse_score__lte', 1)) | models.Q(('impulse_score__isnull', True)),
                name='valid_impulse_score',
            ),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(
                condition=models.Q(('regret_score__gte', 0), ('regret_score__lte', 1)) | models.Q(('regret_score__isnull', True)),
                name='valid_regret_score',
            ),
        ),
    ]