# Generated by Codex on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transactionreflection"),
        ("transactions", "0004_rename_transaction_user_regret_idx_transaction_user_id_a36c24_idx_and_more"),
    ]

    operations = []
