# Generated by Django 4.2.27 on 2026-02-01 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("spend", "Spend"),
                            ("income", "Income"),
                            ("refund", "Refund"),
                        ],
                        default="spend",
                        max_length=16,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("occurred_at", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("subscriptions", "Subscriptions"),
                            ("groceries", "Groceries"),
                            ("eating_out", "Eating Out"),
                            ("transport", "Transport"),
                            ("shopping", "Shopping"),
                            ("bills", "Bills"),
                            ("entertainment", "Entertainment"),
                            ("health", "Health"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(
                        choices=[
                            ("card", "Card"),
                            ("cash", "Cash"),
                            ("online", "Online"),
                            ("bank", "Bank Transfer"),
                            ("other", "Other"),
                        ],
                        default="card",
                        max_length=16,
                    ),
                ),
                (
                    "description_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw bank/merchant description or user-entered note.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="subscriptions.merchant",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link if this transaction is a known subscription charge.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="transaction_user_id_06f072_idx",
                    ),
                    models.Index(
                        fields=["user", "category", "occurred_at"],
                        name="transaction_user_id_d7cd04_idx",
                    ),
                    models.Index(
                        fields=["subscription", "occurred_at"],
                        name="transaction_subscri_aae7b6_idx",
                    ),
                    models.Index(
                        fields=["merchant", "occurred_at"],
                        name="transaction_merchan_aaa8ed_idx",
                    ),
                ],
            },
        ),
    ]
