# Generated by Django 6.0.1 on 2026-03-11 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionReflection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reflected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "regret_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("was_worth_it", models.BooleanField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("reflected_same_day", models.BooleanField(default=False)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflections",
                        to="transactions.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_reflections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reflected_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "reflected_at"],
                        name="transaction_user_id_f6145c_idx",
                    ),
                    models.Index(
                        fields=["transaction", "reflected_at"],
                        name="transaction_transac_7e41d2_idx",
                    ),
                    models.Index(
                        fields=["user", "reflected_same_day"],
                        name="transaction_user_id_d8ce71_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "transaction"),
                        name="uniq_user_transaction_reflection",
                    )
                ],
            },
        ),
    ]
