# Generated by Django 6.0.2 on 2026-02-16 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_add_feedback_and_behavioral_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_user_id_a36c24_idx",
            old_name="transaction_user_regret_idx",
        ),
        migrations.RenameIndex(
            model_name="transaction",
            new_name="transaction_user_id_478123_idx",
            old_name="transaction_user_satisfaction_idx",
        ),
    ]
