# Generated by Django 6.0.1 on 2026-04-01 03:18

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_merge_20260325_1248"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="considered_at",
            field=zapp.security.encrypted_fields.EncryptedDateTimeField(
                blank=True,
                help_text="When user started considering this purchase (for decision time calculation)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description_raw",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Raw bank/merchant description or user-entered note.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="feedback_confidence",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 confidence in feedback_value_score",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="feedback_value_score",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 derived from reflection_text + ratings (user feedback on value)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="impulse_score",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 computed impulse likelihood for this transaction",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reflection_text",
            field=zapp.security.encrypted_fields.EncryptedTextField(
                blank=True,
                help_text="User's thoughts/notes about this purchase",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="regret_rating",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True,
                help_text="0-100 scale: level of regret about this purchase",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="regret_score",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 computed regret likelihood for this transaction",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="repurchase_likelihood",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, help_text="0-100 scale: likelihood to buy again", null=True
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="satisfaction_rating",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True,
                help_text="1-10 scale: how satisfied with this purchase",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="self_report_researched",
            field=zapp.security.encrypted_fields.EncryptedBooleanField(
                blank=True,
                help_text="Did user report researching before buying (nullable = not asked)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="usage_frequency",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True,
                help_text="How often user expects to use this (e.g., times per week)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionreflection",
            name="notes",
            field=zapp.security.encrypted_fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transactionreflection",
            name="regret_score",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="transactionreflection",
            name="was_worth_it",
            field=zapp.security.encrypted_fields.EncryptedBooleanField(
                blank=True, null=True
            ),
        ),
    ]
