# Generated by Django 6.0.1 on 2026-04-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_satisfaction_rating",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_regret_rating",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_repurchase_likelihood",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_impulse_score",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_regret_score",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_feedback_value_score",
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="valid_feedback_confidence",
        ),
    ]
