# Generated by Django 6.0.1 on 2026-04-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_alter_transaction_amount_and_more"),
    ]

    operations = []
