# Generated by Django 6.0.1 on 2026-02-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usercomputed_userrawexplicit_userrawinferred_and_more'),
    ]

    operations = []
