# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_userrawinferred_data_sufficiency_tier"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userpreference",
            name="users_userp_user_id_0c4075_idx",
        ),
    ]
