# Generated by Django 6.0.1 on 2026-02-02 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_alter_merchant_id_alter_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'version'], name='valuations__name_9fb73c_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SubscriptionValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence', models.FloatField(default=1.0)),
                ('explanation_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_valuations', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_valuations', to='valuations.valuationmodelversion')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['user', 'period_end'], name='valuations__user_id_15345d_idx'), models.Index(fields=['user', 'subscription', 'period_end'], name='valuations__user_id_b2823c_idx'), models.Index(fields=['subscription', 'period_end'], name='valuations__subscri_0fa544_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_category', models.CharField(blank=True, max_length=64)),
                ('estimated_fair_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('personal_value_score', models.PositiveSmallIntegerField()),
                ('recommendation', models.CharField(choices=[('buy', 'Buy'), ('wait', 'Wait'), ('skip', 'Skip'), ('alternative', 'Alternative')], default='wait', max_length=16)),
                ('reasoning_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_valuations', to=settings.AUTH_USER_MODEL)),
                ('model_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_valuations', to='valuations.valuationmodelversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='valuations__user_id_d87826_idx'), models.Index(fields=['user', 'recommendation', 'created_at'], name='valuations__user_id_bfad3b_idx'), models.Index(fields=['item_name', 'created_at'], name='valuations__item_na_8db7f2_idx')],
            },
        ),
    ]
