# Generated by Django 6.0.1 on 2026-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuations', '0002_alter_itemvaluation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionvaluation',
            name='context',
            field=models.CharField(choices=[('subscription_renewal', 'Subscription Renewal'), ('subscription_cancel', 'Subscription Cancel'), ('one_off_purchase', 'One-off Purchase'), ('upgrade', 'Upgrade'), ('other', 'Other')], default='subscription_renewal', help_text='What triggered this valuation', max_length=32),
        ),
        migrations.AddField(
            model_name='subscriptionvaluation',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('wait', 'Wait'), ('skip', 'Skip'), ('alternative', 'Alternative')], help_text='Buy/Wait/Skip/Alternative recommendation', max_length=16),
        ),
        migrations.AlterField(
            model_name='subscriptionvaluation',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='0-1 confidence score for this valuation'),
        ),
        migrations.AddField(
            model_name='subscriptionvaluation',
            name='evidence_json',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of inputs used: weights, raw data, computed metrics'),
        ),
        migrations.AddField(
            model_name='itemvaluation',
            name='context',
            field=models.CharField(choices=[('subscription_renewal', 'Subscription Renewal'), ('subscription_cancel', 'Subscription Cancel'), ('one_off_purchase', 'One-off Purchase'), ('upgrade', 'Upgrade'), ('other', 'Other')], default='one_off_purchase', help_text='What triggered this valuation', max_length=32),
        ),
        migrations.AddField(
            model_name='itemvaluation',
            name='observed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price the user is considering paying', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemvaluation',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='0-1 confidence score for this valuation'),
        ),
        migrations.AddField(
            model_name='itemvaluation',
            name='evidence_json',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of inputs: computed weights, raw explicit/inferred data'),
        ),
        migrations.AddIndex(
            model_name='subscriptionvaluation',
            index=models.Index(fields=['recommendation'], name='valuations_subscription_recommendation_idx'),
        ),
        migrations.AddIndex(
            model_name='itemvaluation',
            index=models.Index(fields=['recommendation'], name='valuations_item_recommendation_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionvaluation',
            constraint=models.UniqueConstraint(fields=('user', 'subscription', 'period_start', 'period_end', 'model_version'), name='uniq_subscription_valuation'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionvaluation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='valid_subscription_confidence'),
        ),
        migrations.AddConstraint(
            model_name='itemvaluation',
            constraint=models.CheckConstraint(condition=models.Q(('personal_value_score__gte', 0), ('personal_value_score__lte', 100)), name='valid_personal_value_score'),
        ),
        migrations.AddConstraint(
            model_name='itemvaluation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='valid_item_confidence'),
        ),
    ]