# Generated by Django 6.0.2 on 2026-03-12 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_add_feedback_and_valuation_fields"),
        (
            "valuations",
            "0004_rename_valuations_item_recommendation_idx_valuations__recomme_7a0353_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="itemvaluation",
            name="valid_personal_value_score",
        ),
        migrations.AddField(
            model_name="subscriptionvaluation",
            name="personal_value_score",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="0-150 personalized fit score (match ~100, underused <80, extremely useful >100)",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="itemvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("personal_value_score__gte", 0), ("personal_value_score__lte", 150)
                ),
                name="valid_personal_value_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("personal_value_score__gte", 0),
                    ("personal_value_score__lte", 150),
                )
                | models.Q(("personal_value_score__isnull", True)),
                name="valid_subscription_personal_value_score",
            ),
        ),
    ]
