# Generated by Django 6.0.2 on 2026-03-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0005_add_feedback_and_valuation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvaluation",
            name="personal_value_score",
            field=models.PositiveSmallIntegerField(
                help_text="0-150 personalized fit score (match ~100, underused <80, extremely useful >100)"
            ),
        ),
    ]
