# Generated by Django 6.0.2 on 2026-03-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0007_subscriptionvaluation_utilization_cost_benefit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscriptionvaluation",
            name="valid_subscriptionvaluation_utilization",
        ),
        migrations.RemoveConstraint(
            model_name="subscriptionvaluation",
            name="valid_subscriptionvaluation_cost_benefit",
        ),
        migrations.RemoveField(
            model_name="subscriptionvaluation",
            name="subscription_utilization",
        ),
        migrations.RemoveField(
            model_name="subscriptionvaluation",
            name="subscription_cost_benefit",
        ),
    ]
