# Generated by Django 6.0.1 on 2026-04-01 03:55

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("valuations", "0008_remove_subscriptionvaluation_utilization_cost_benefit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvaluation",
            name="estimated_fair_price",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, help_text="Market-based fair price estimate", null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="evidence_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of inputs: computed weights, raw explicit/inferred data",
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="item_category",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True, max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="item_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="observed_price",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(
                blank=True, help_text="Price the user is considering paying", null=True
            ),
        ),
        migrations.AlterField(
            model_name="itemvaluation",
            name="reasoning_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="UI-friendly reasoning: pros, cons, alternatives",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="estimated_value",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="evidence_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Snapshot of inputs used: weights, raw data, computed metrics",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="explanation_json",
            field=zapp.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="UI-friendly explanation: summary, drivers, pros/cons",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="net_value",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name="subscriptionvaluation",
            name="total_cost",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
    ]
