# Generated by Django 6.0.1 on 2026-04-08 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Keep the historical boundary at 0007 so previously applied databases
        # remain consistent; subscriptions.0008 handles its own PG transaction
        # behavior and no longer needs integrations ordered after it.
        ("subscriptions", "0007_subscription_utilization_cost_benefit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyConnection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "spotify_user_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("spotify_uri", models.CharField(blank=True, max_length=128)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("country", models.CharField(blank=True, max_length=8)),
                (
                    "product",
                    models.CharField(
                        blank=True,
                        help_text="Spotify product / account type (e.g. premium, free).",
                        max_length=32,
                    ),
                ),
                ("granted_scopes", models.TextField(blank=True)),
                ("access_token_encrypted", models.TextField(blank=True)),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "OK"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True, null=True)),
                ("raw_profile_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotifySyncRun",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "OK"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="integrations.spotifyconnection",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_sync_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyRawPayload",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "payload_type",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("recently_played", "Recently played"),
                            ("player", "Playback state"),
                            ("currently_playing", "Currently playing"),
                            ("top_tracks", "Top tracks"),
                            ("top_artists", "Top artists"),
                            ("saved_tracks", "Saved tracks"),
                        ],
                        max_length=32,
                    ),
                ),
                ("raw_json", models.JSONField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_raw_payloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_payloads",
                        to="integrations.spotifysyncrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyPlayEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("played_at", models.DateTimeField(db_index=True)),
                ("track_id", models.CharField(db_index=True, max_length=64)),
                ("track_uri", models.CharField(blank=True, max_length=128)),
                ("track_name", models.CharField(blank=True, max_length=512)),
                ("artist_name", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_play_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_events",
                        to="integrations.spotifysyncrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpotifyFeatureSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("feature_version", models.PositiveSmallIntegerField(default=1)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_category",
                    models.CharField(
                        db_index=True,
                        default="entertainment.streaming_music",
                        max_length=64,
                    ),
                ),
                ("features", models.JSONField()),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spotify_feature_snapshots",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spotify_feature_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sync_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_snapshots",
                        to="integrations.spotifysyncrun",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="spotifyconnection",
            index=models.Index(
                fields=["spotify_user_id"], name="integration_spotify_5e8802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spotifyconnection",
            index=models.Index(
                fields=["sync_status"], name="integration_sync_st_c982dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spotifysyncrun",
            index=models.Index(
                fields=["user", "-started_at"], name="integration_user_id_dc28aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spotifyrawpayload",
            index=models.Index(
                fields=["user", "payload_type", "-fetched_at"],
                name="integration_user_id_11a485_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="spotifyplayevent",
            index=models.Index(
                fields=["user", "-played_at"], name="integration_user_id_108183_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="spotifyplayevent",
            constraint=models.UniqueConstraint(
                fields=("user", "track_id", "played_at"),
                name="uniq_spotify_play_user_track_time",
            ),
        ),
        migrations.AddIndex(
            model_name="spotifyfeaturesnapshot",
            index=models.Index(
                fields=["user", "-computed_at"], name="integration_user_id_2a89c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spotifyfeaturesnapshot",
            index=models.Index(
                fields=["canonical_category", "-computed_at"],
                name="integration_canonic_fc0cd9_idx",
            ),
        ),
    ]
