# Generated by Django 6.0.1 on 2026-04-08 23:39

from django.db import migrations, models


def migrate_pending_connections_to_idle(apps, schema_editor):
    SpotifyConnection = apps.get_model("integrations", "SpotifyConnection")
    SpotifyConnection.objects.filter(
        sync_status="pending",
        last_synced_at__isnull=True,
    ).update(sync_status="idle")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifyconnection",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("syncing", "Syncing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("pending", "Pending"),
                ],
                default="idle",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="spotifysyncrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("syncing", "Syncing"),
                    ("ok", "OK"),
                    ("error", "Error"),
                    ("pending", "Pending"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(migrate_pending_connections_to_idle, noop_reverse),
    ]
