# Generated by Django 6.0.2 on 2026-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_merchant_subscription_eligibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_cost_benefit",
            field=models.FloatField(
                blank=True,
                help_text="0-1 bounded value-vs-cost score derived from valuation runs.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_utilization",
            field=models.FloatField(
                blank=True,
                help_text="0-1 normalized utilization score derived from valuation runs.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("subscription_utilization__gte", 0), ("subscription_utilization__lte", 1)),
                    ("subscription_utilization__isnull", True),
                    _connector="OR",
                ),
                name="valid_subscription_utilization",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("subscription_cost_benefit__gte", 0), ("subscription_cost_benefit__lte", 1)),
                    ("subscription_cost_benefit__isnull", True),
                    _connector="OR",
                ),
                name="valid_subscription_cost_benefit",
            ),
        ),
    ]
