# Generated by Django 6.0.1 on 2026-04-01 03:18

import zapp.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscription_utilization_cost_benefit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="cancelled_on",
            field=zapp.security.encrypted_fields.EncryptedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="feedback_confidence",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 confidence in feedback_value_score",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="feedback_value_score",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 derived from reflection_text + ratings (user feedback on value)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="notes",
            field=zapp.security.encrypted_fields.EncryptedTextField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan_name",
            field=zapp.security.encrypted_fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="price",
            field=zapp.security.encrypted_fields.EncryptedDecimalField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="reactivation_count",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                default=0,
                help_text="Number of times this subscription has been reactivated",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="renewal_date",
            field=zapp.security.encrypted_fields.EncryptedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="started_on",
            field=zapp.security.encrypted_fields.EncryptedDateField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_cost_benefit",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 bounded value-vs-cost score derived from valuation runs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subscription_utilization",
            field=zapp.security.encrypted_fields.EncryptedFloatField(
                blank=True,
                help_text="0-1 normalized utilization score derived from valuation runs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="usage_frequency",
            field=zapp.security.encrypted_fields.EncryptedIntegerField(
                blank=True, help_text="Uses per week or your chosen unit", null=True
            ),
        ),
    ]
