# Generated by Django 6.0.1 on 2026-04-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_alter_subscription_cancelled_on_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_subscription_feedback_value_score",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_subscription_feedback_confidence",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_subscription_utilization",
        ),
        migrations.RemoveConstraint(
            model_name="subscription",
            name="valid_subscription_cost_benefit",
        ),
    ]
