# Generated by Django 6.0.1 on 2026-04-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_alter_subscription_cancelled_on_and_more"),
    ]

    operations = []
