# Generated by Django 6.0.1 on 2026-04-01 03:24

from django.db import migrations


CONSTRAINT_NAMES = (
    "valid_subscription_feedback_value_score",
    "valid_subscription_feedback_confidence",
    "valid_subscription_utilization",
    "valid_subscription_cost_benefit",
)


def _drop_legacy_numeric_constraints():
    return [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "subscriptions_subscription" '
                f'DROP CONSTRAINT IF EXISTS "{constraint_name}";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        )
        for constraint_name in CONSTRAINT_NAMES
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_alter_subscription_cancelled_on_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=_drop_legacy_numeric_constraints(),
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="subscription",
                    name="valid_subscription_feedback_value_score",
                ),
                migrations.RemoveConstraint(
                    model_name="subscription",
                    name="valid_subscription_feedback_confidence",
                ),
                migrations.RemoveConstraint(
                    model_name="subscription",
                    name="valid_subscription_utilization",
                ),
                migrations.RemoveConstraint(
                    model_name="subscription",
                    name="valid_subscription_cost_benefit",
                ),
            ],
        ),
    ]
