# Generated by Django 6.0.1 on 2026-04-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_alter_subscription_usage_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="category",
            field=models.CharField(
                choices=[
                    ("streaming", "Streaming"),
                    ("grocery", "Grocery"),
                    ("fitness", "Fitness"),
                    ("software", "Software"),
                    ("utilities", "Utilities"),
                    ("food", "Food & Delivery"),
                    ("education", "Education"),
                    ("health", "Health & Pharmacy"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=32,
            ),
        ),
    ]
