# Generated by Django 6.0.1 on 2026-04-01 03:55

import core.security.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai",
            "0005_rename_ai_conversa_user_id_a20ca5_idx_ai_conversa_user_id_cd2eba_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="session_state_json",
            field=core.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Structured short-term memory for active goals, entities, and open loops.",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="summary_text",
            field=core.security.encrypted_fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Rolling summary of older turns kept in the short-term memory store.",
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=core.security.encrypted_fields.EncryptedCharField(
                blank=True,
                help_text="Optional human-readable title for the conversation.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="conversationmemoryitem",
            name="detail_json",
            field=core.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Optional structured details extracted from the turn.",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmemoryitem",
            name="summary_text",
            field=core.security.encrypted_fields.EncryptedTextField(
                help_text="Short retrieval-friendly summary of the memory."
            ),
        ),
        migrations.AlterField(
            model_name="conversationmemoryitem",
            name="tags_json",
            field=core.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=list,
                help_text="Normalized tags used for lightweight retrieval.",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=core.security.encrypted_fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="metadata_json",
            field=core.security.encrypted_fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Optional metadata (tool calls, citations, extracted facts).",
            ),
        ),
        migrations.AlterField(
            model_name="userfact",
            name="fact_value_json",
            field=core.security.encrypted_fields.EncryptedJSONField(
                default=dict, help_text="Structured representation of the fact."
            ),
        ),
    ]
