# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_alter_conversation_session_state_json_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userfact",
            name="ai_userfact_user_id_9575a5_idx",
        ),
    ]
