# Generated by Django 6.0.1 on 2026-02-02 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0002_alter_merchant_id_alter_subscription_id'),
        ('valuations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional human-readable title for the conversation.', max_length=255, null=True)),
                ('context_type', models.CharField(choices=[('general', 'General'), ('subscription', 'Subscription'), ('product', 'Product'), ('budgeting', 'Budgeting')], default='general', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_item_valuation', models.ForeignKey(blank=True, help_text='Set if this conversation is about a purchase decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='valuations.itemvaluation')),
                ('linked_subscription', models.ForeignKey(blank=True, help_text='Set if this conversation is about a specific subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Optional metadata (tool calls, citations, extracted facts).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_key', models.CharField(help_text="Canonical key, e.g. 'values_convenience'.", max_length=128)),
                ('fact_value_json', models.JSONField(default=dict, help_text='Structured representation of the fact.')),
                ('source', models.CharField(default='chat', help_text='chat / onboarding / inferred', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.8, help_text='Confidence score between 0 and 1.', max_digits=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'updated_at'], name='ai_conversa_user_id_4c2c28_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_message_convers_0cc073_idx'),
        ),
        migrations.AddIndex(
            model_name='userfact',
            index=models.Index(fields=['user', 'fact_key'], name='ai_userfact_user_id_9575a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfact',
            unique_together={('user', 'fact_key')},
        ),
    ]
