# Generated by Django 6.0.1 on 2026-04-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_conversationmemoryitem"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversationmemoryitem",
            new_name="ai_conversa_user_id_cd2eba_idx",
            old_name="ai_conversa_user_id_a20ca5_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmemoryitem",
            new_name="ai_conversa_user_id_df3597_idx",
            old_name="ai_conversa_user_id_27ae94_idx",
        ),
        migrations.RenameIndex(
            model_name="conversationmemoryitem",
            new_name="ai_conversa_convers_90711f_idx",
            old_name="ai_conversa_convers_1a03db_idx",
        ),
    ]
