# Generated by Django 6.0.1 on 2026-03-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bankaccount",
            new_name="banking_ban_connect_660465_idx",
            old_name="banking_ban_connect_9a2c4e_idx",
        ),
        migrations.RenameIndex(
            model_name="bankconnection",
            new_name="banking_ban_user_id_539e2f_idx",
            old_name="banking_ban_user_id_7a8f3d_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="banking_ban_user_id_0a7ae2_idx",
            old_name="banking_ban_user_id_2b8e1f_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="banking_ban_account_d2144d_idx",
            old_name="banking_ban_account_3c9d5e_idx",
        ),
        migrations.RenameIndex(
            model_name="banktransaction",
            new_name="banking_ban_user_id_80a20e_idx",
            old_name="banking_ban_user_id_4d7a2e_idx",
        ),
    ]
