# Generated by Django 6.0.1 on 2026-03-11 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "banking",
            "0002_rename_banking_ban_connect_9a2c4e_idx_banking_ban_connect_660465_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionBehavioralTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="category_source",
            field=models.CharField(
                blank=True,
                help_text="Source of assigned category: plaid, merchant_override, zapp_mapping, user_override",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="user_override_category",
            field=models.CharField(
                blank=True,
                help_text="User-assigned category; takes precedence over Zapp categories",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="zapp_primary_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("housing_living", "Housing & Living"),
                    ("utilities_bills", "Utilities & Bills"),
                    ("groceries_essentials", "Groceries & Essentials"),
                    ("dining_cafes", "Dining & Cafes"),
                    ("transportation", "Transportation"),
                    ("shopping", "Shopping"),
                    ("subscriptions", "Subscriptions"),
                    ("entertainment_social", "Entertainment & Social"),
                    ("health_wellness", "Health & Wellness"),
                    ("education_career", "Education & Career"),
                    ("travel", "Travel"),
                    ("family_gifts", "Family & Gifts"),
                    ("financial_transfers", "Financial & Transfers"),
                    ("income", "Income"),
                    ("miscellaneous", "Miscellaneous / Unclassified"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="zapp_subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("groceries", "Groceries"),
                    ("household_supplies", "Household Supplies"),
                    ("toiletries", "Toiletries"),
                    ("pharmacy_essentials", "Pharmacy Essentials"),
                    ("coffee", "Coffee"),
                    ("takeout", "Takeout"),
                    ("fast_food", "Fast Food"),
                    ("restaurants", "Restaurants"),
                    ("delivery", "Delivery"),
                    ("snacks_dessert", "Snacks / Dessert"),
                    ("clothing", "Clothing"),
                    ("tech", "Tech"),
                    ("home_decor", "Home Decor"),
                    ("personal_items", "Personal Items"),
                    ("impulse_purchase", "Impulse Purchase"),
                    ("general", "General"),
                    ("streaming", "Streaming"),
                    ("music", "Music"),
                    ("software", "Software"),
                    ("productivity_tools", "Productivity Tools"),
                    ("software_productivity", "Software / Productivity"),
                    ("fitness_membership", "Fitness Membership"),
                    ("cloud_storage", "Cloud / Storage"),
                    ("games", "Games"),
                    ("nightlife", "Nightlife"),
                    ("events", "Events"),
                    ("hobbies", "Hobbies"),
                    ("movies", "Movies"),
                    ("ride_share", "Ride Share"),
                    ("savings_transfer", "Savings Transfer"),
                    ("credit_card_payment", "Credit Card Payment"),
                    ("peer_transfer", "Peer Transfer"),
                    ("investing_transfer", "Investing Transfer"),
                    ("atm_cash", "ATM / Cash Withdrawal"),
                    ("payroll", "Payroll"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="MerchantCategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_pattern",
                    models.CharField(
                        help_text="Substring or pattern to match against normalized merchant/name",
                        max_length=256,
                    ),
                ),
                (
                    "zapp_primary_category",
                    models.CharField(
                        choices=[
                            ("housing_living", "Housing & Living"),
                            ("utilities_bills", "Utilities & Bills"),
                            ("groceries_essentials", "Groceries & Essentials"),
                            ("dining_cafes", "Dining & Cafes"),
                            ("transportation", "Transportation"),
                            ("shopping", "Shopping"),
                            ("subscriptions", "Subscriptions"),
                            ("entertainment_social", "Entertainment & Social"),
                            ("health_wellness", "Health & Wellness"),
                            ("education_career", "Education & Career"),
                            ("travel", "Travel"),
                            ("family_gifts", "Family & Gifts"),
                            ("financial_transfers", "Financial & Transfers"),
                            ("income", "Income"),
                            ("miscellaneous", "Miscellaneous / Unclassified"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "zapp_subcategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("groceries", "Groceries"),
                            ("household_supplies", "Household Supplies"),
                            ("toiletries", "Toiletries"),
                            ("pharmacy_essentials", "Pharmacy Essentials"),
                            ("coffee", "Coffee"),
                            ("takeout", "Takeout"),
                            ("fast_food", "Fast Food"),
                            ("restaurants", "Restaurants"),
                            ("delivery", "Delivery"),
                            ("snacks_dessert", "Snacks / Dessert"),
                            ("clothing", "Clothing"),
                            ("tech", "Tech"),
                            ("home_decor", "Home Decor"),
                            ("personal_items", "Personal Items"),
                            ("impulse_purchase", "Impulse Purchase"),
                            ("general", "General"),
                            ("streaming", "Streaming"),
                            ("music", "Music"),
                            ("software", "Software"),
                            ("productivity_tools", "Productivity Tools"),
                            ("software_productivity", "Software / Productivity"),
                            ("fitness_membership", "Fitness Membership"),
                            ("cloud_storage", "Cloud / Storage"),
                            ("games", "Games"),
                            ("nightlife", "Nightlife"),
                            ("events", "Events"),
                            ("hobbies", "Hobbies"),
                            ("movies", "Movies"),
                            ("ride_share", "Ride Share"),
                            ("savings_transfer", "Savings Transfer"),
                            ("credit_card_payment", "Credit Card Payment"),
                            ("peer_transfer", "Peer Transfer"),
                            ("investing_transfer", "Investing Transfer"),
                            ("atm_cash", "ATM / Cash Withdrawal"),
                            ("payroll", "Payroll"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Higher = applied first; use for more specific overrides",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "match_pattern"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="banking_mer_is_acti_1d0c84_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BankTransactionBehavioralTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavioral_tags_link",
                        to="banking.banktransaction",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="banking.transactionbehavioraltag",
                    ),
                ),
            ],
            options={
                "unique_together": {("transaction", "tag")},
            },
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="behavioral_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="bank_transactions",
                through="banking.BankTransactionBehavioralTag",
                to="banking.transactionbehavioraltag",
            ),
        ),
    ]
