# Generated by Django 6.0.1 on 2026-06-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0008_alter_bankaccount_available_balance_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bankaccount",
            name="banking_ban_connect_660465_idx",
        ),
    ]
