# Generated by Django 6.0.1 on 2026-03-11 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="streak",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("best_streak_days", models.PositiveIntegerField(default=0)),
                ("last_checkin_date", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("reflection", "Reflection"),
                            ("advisor", "Advisor"),
                            ("subscription", "Subscription"),
                            ("social", "Social"),
                            ("streak", "Streak"),
                        ],
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="gamificatio_categor_508954_idx",
                    ),
                    models.Index(fields=["code"], name="gamificatio_code_edd252_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("invite_code", models.CharField(max_length=12, unique=True)),
                ("is_private", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("member", "Member")],
                        default="member",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="gamification.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("log_purchase", "Log purchase"),
                            ("reflect_same_day", "Reflect same day"),
                            ("use_advisor", "Use advisor"),
                            ("weekly_review", "Complete weekly review"),
                            ("add_subscription", "Add subscription"),
                            ("cancel_subscription", "Cancel subscription"),
                            ("pause_subscription", "Pause subscription"),
                            ("complete_onboarding", "Complete onboarding"),
                            ("set_monthly_target", "Set monthly target"),
                            ("complete_monthly_target", "Complete monthly target"),
                            ("complete_monthly_review", "Complete monthly review"),
                            (
                                "run_subscription_valuation",
                                "Run subscription valuation",
                            ),
                            ("run_item_valuation", "Run item valuation"),
                            ("join_group", "Join group"),
                            ("create_group", "Create group"),
                        ],
                        max_length=48,
                    ),
                ),
                ("points", models.IntegerField()),
                ("source_object_type", models.CharField(blank=True, max_length=32)),
                ("source_object_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "event_key",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("window_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_events",
                        to="gamification.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                ("source_object_type", models.CharField(blank=True, max_length=32)),
                ("source_object_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="gamification.badge",
                    ),
                ),
                (
                    "trigger_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_badges",
                        to="gamification.pointevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["invite_code"], name="gamificatio_invite__7654b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["created_at"], name="gamificatio_created_6ef58e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["group", "joined_at"], name="gamificatio_group_i_bb55dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["user", "joined_at"], name="gamificatio_user_id_18c2e4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="uniq_group_member"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["user", "created_at"], name="gamificatio_user_id_4f9bc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["user", "action", "created_at"],
                name="gamificatio_user_id_d3d8c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["group", "created_at"], name="gamificatio_group_i_26bbff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["group", "action", "created_at"],
                name="gamificatio_group_i_00d6ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["user", "window_date"], name="gamificatio_user_id_96f734_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["group", "window_date"], name="gamificatio_group_i_1e733e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointevent",
            index=models.Index(
                fields=["event_key"], name="gamificatio_event_k_b535f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["user", "awarded_at"], name="gamificatio_user_id_dd5f82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userbadge",
            index=models.Index(
                fields=["badge", "awarded_at"], name="gamificatio_badge_i_ece716_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userbadge",
            constraint=models.UniqueConstraint(
                fields=("user", "badge"), name="uniq_user_badge"
            ),
        ),
    ]
